- src/main/java/nl/talsmasoftware/umldoclet/config/UMLDocletConfig.java
- src/test/java/nl/talsmasoftware/umldoclet/config/UMLDocletConfigTest.java
Added test to reproduce the behaviour.
Fixed #37.
Failing test now passes.
> Fix package private defaultconfig.

- USAGE.md
> Document maven JavaDoc plugin 3.0.0

- src/main/java/nl/talsmasoftware/umldoclet/javadoc/TypeNameVisitor.java
- src/test/java/nl/talsmasoftware/umldoclet/issues/Bug75StackOverflowTest.java
> Fix StackOverflowError in TypeNameVisitor

- src/main/java/nl/talsmasoftware/umldoclet/uml/Type.java
- src/test/java/nl/talsmasoftware/umldoclet/issues/Bug74DuplicateGenericsTest.java
> Fix double generics in name of ClassDiagrams

- src/main/java/nl/talsmasoftware/umldoclet/UMLDoclet.java
- src/main/java/nl/talsmasoftware/umldoclet/html/UmlClassDiagram.java
- src/main/java/nl/talsmasoftware/umldoclet/html/UmlPackageDiagram.java
- src/main/java/nl/talsmasoftware/umldoclet/rendering/plantuml/PlantumlImage.java
- src/main/java/nl/talsmasoftware/umldoclet/rendering/plantuml/PlantumlImageWriter.java
- src/main/java/nl/talsmasoftware/umldoclet/uml/PackageDiagram.java
- src/main/java/nl/talsmasoftware/umldoclet/uml/Type.java
- src/test/java/nl/talsmasoftware/umldoclet/issues/Issue25ImagedirTest.java
- src/test/java/nl/talsmasoftware/umldoclet/issues/Issue64Test.java
- src/test/java/nl/talsmasoftware/umldoclet/issues/Issue69LinksTest.java
- src/test/java/nl/talsmasoftware/umldoclet/rendering/plantuml/PlantumlImageTest.java
> Implement links from diagrams to javadoc HTML

- src/main/java/nl/talsmasoftware/umldoclet/uml/TypeName.java
- src/test/java/nl/talsmasoftware/umldoclet/issues/Bug75StackOverflowTest.java
- src/test/java/nl/talsmasoftware/umldoclet/issues/Bug79GenericsAsMarkupTest.java
- src/test/java/nl/talsmasoftware/umldoclet/issues/Issue30JavaBeanPropertiesTest.java
- src/test/java/nl/talsmasoftware/umldoclet/issues/Issue64ExtendsObjectTest.java
- src/test/java/nl/talsmasoftware/umldoclet/issues/Issue69LinksTest.java
- src/test/java/nl/talsmasoftware/umldoclet/issues/Issue70ConfigurableFormatTest.java
- src/test/java/nl/talsmasoftware/umldoclet/issues/Issue71DeprecationTest.java
- src/test/java/nl/talsmasoftware/umldoclet/issues/Issue72DefaultConstructorTest.java
> Fix certain generic types render as PlantUML markup

- docs/README.md
> Document the requirement for graphviz

- src/main/java/nl/talsmasoftware/umldoclet/html/UmlClassDiagram.java
- src/main/java/nl/talsmasoftware/umldoclet/html/UmlPackageDiagram.java
> HTML: Add "white-space:pre-wrap" to first <pre> after class diagram

- src/main/java/nl/talsmasoftware/umldoclet/html/UmlClassDiagram.java
- src/main/java/nl/talsmasoftware/umldoclet/html/UmlPackageDiagram.java
This PR is the V1 merge of #122
> HTML: Add "white-space:pre-wrap" to first <pre> after class diagram (v1)

- src/main/java/nl/talsmasoftware/umldoclet/javadoc/UMLFactory.java
- src/main/java/nl/talsmasoftware/umldoclet/uml/ClassUml.java
- src/main/java/nl/talsmasoftware/umldoclet/uml/Field.java
- src/main/java/nl/talsmasoftware/umldoclet/uml/Link.java
- src/main/java/nl/talsmasoftware/umldoclet/uml/Method.java
- src/main/java/nl/talsmasoftware/umldoclet/uml/Parameters.java
- src/main/java/nl/talsmasoftware/umldoclet/uml/Type.java
- src/main/java/nl/talsmasoftware/umldoclet/uml/TypeMember.java
- src/test/java/nl/talsmasoftware/umldoclet/javadoc/Issue84TypeVariableResolutionTest.java
> Typename variable resolution

- src/main/java/nl/talsmasoftware/umldoclet/javadoc/UMLFactory.java
- src/test/java/nl/talsmasoftware/umldoclet/features/Issue152InnerClassIncludeVisibilityTest.java
- src/test/java/nl/talsmasoftware/umldoclet/features/PublicClass.java
Added a unit test that verifies the desired behaviour
> Fix #152 by filtering on 'isIncluded' for inner classes too

- docs/README.md
Signed-off-by: Sjoerd Talsma <sjoerd@talsma-ict.nl>
> Add LGTM badge

- .travis.yml
- pom.xml
This fixes #174 
Signed-off-by: Sjoerd Talsma <sjoerd@talsma-ict.nl>
> Add reports to assist codacy analysis

- src/main/java/nl/talsmasoftware/umldoclet/javadoc/UMLOptions.java
- src/main/java/nl/talsmasoftware/umldoclet/javadoc/dependencies/DependenciesElementScanner.java
- src/main/java/nl/talsmasoftware/umldoclet/uml/DependencyDiagram.java
- src/main/resources/nl/talsmasoftware/umldoclet/UMLDoclet.properties
- src/test/java/nl/talsmasoftware/umldoclet/javadoc/DocletConfigTest.java
- src/test/java/nl/talsmasoftware/umldoclet/javadoc/dependencies/PackageDependenciesTest.java
- src/test/java/nl/talsmasoftware/umldoclet/uml/DependencyDiagramTest.java
> Add configuration option `-umlExcludedPackageDependencies`

- src/main/java/nl/talsmasoftware/umldoclet/configuration/FieldConfig.java
- src/main/java/nl/talsmasoftware/umldoclet/configuration/ImageConfig.java
- src/main/java/nl/talsmasoftware/umldoclet/configuration/MethodConfig.java
- src/main/java/nl/talsmasoftware/umldoclet/configuration/Visibility.java
- src/main/java/nl/talsmasoftware/umldoclet/html/DiagramCollector.java
- src/main/java/nl/talsmasoftware/umldoclet/javadoc/DocletConfig.java
- src/main/java/nl/talsmasoftware/umldoclet/javadoc/UMLFactory.java
- src/main/java/nl/talsmasoftware/umldoclet/uml/Diagram.java
- src/main/java/nl/talsmasoftware/umldoclet/uml/TypeMember.java
- src/test/java/nl/talsmasoftware/umldoclet/javadoc/DocletConfigTest.java
- src/test/java/nl/talsmasoftware/umldoclet/uml/ClassDiagramTest.java
- src/test/java/nl/talsmasoftware/umldoclet/uml/DependencyDiagramTest.java
- src/test/java/nl/talsmasoftware/umldoclet/uml/DiagramTest.java
- src/test/java/nl/talsmasoftware/umldoclet/uml/NamespaceTest.java
- src/test/java/nl/talsmasoftware/umldoclet/uml/TypeMemberTest.java
There are currently two dependency cycles in this project (found because we now have a dependency diagram thanks to #164)
This pull request is intended to remove these cycles.
> Fix dependency cycles

- src/main/java/nl/talsmasoftware/umldoclet/rendering/indent/package-info.java
- src/main/java/nl/talsmasoftware/umldoclet/rendering/package-info.java
- src/main/java/nl/talsmasoftware/umldoclet/rendering/writers/package-info.java
- src/main/java/nl/talsmasoftware/umldoclet/uml/package-info.java
- src/main/java/nl/talsmasoftware/umldoclet/uml/util/package-info.java
- src/main/java/nl/talsmasoftware/umldoclet/util/package-info.java
By no means final, but a step in the right direction, so should be merged to develop
> Merge added javadoc so far

- java-8/src/main/java/nl/talsmasoftware/umldoclet/uml/DependencyDiagram.java
- java-8/src/main/java/nl/talsmasoftware/umldoclet/uml/UMLNode.java
- java-8/src/test/java/nl/talsmasoftware/umldoclet/uml/DependencyDiagramTest.java
- java-9/src/main/java/nl/talsmasoftware/umldoclet/javadoc/dependencies/DependenciesElementScanner.java
> Render excluded package dependencies if the diagram is otherwise empty

- java-8/pom.xml
- java-9/pom.xml
- pom.xml
> Check apache license headers in multi-module project configuration

- readme.md
> Add codebeat badge to readme.md

- src/main/java/nl/talsmasoftware/umldoclet/javadoc/UMLFactory.java
- src/test/java/nl/talsmasoftware/umldoclet/issues/Bug245SubInterfaceTest.java
> Render SubInterface extends ParentInterface as solid line.

- pom.xml
Signed-off-by: Sjoerd Talsma <sjoerd@talsma-ict.nl>
> Upgrade PlantUML version to 1.2020.7

- src/main/java/nl/talsmasoftware/umldoclet/javadoc/DocletConfig.java
- src/test/java/nl/talsmasoftware/umldoclet/javadoc/DocletConfigTest.java
> Keep .puml files in verbose mode

- src/main/java/nl/talsmasoftware/umldoclet/uml/Type.java
- src/test/java/nl/talsmasoftware/umldoclet/issues/Bug276AnnotationSyntaxErrorTest.java
> Do not render children in annotations anymore

- src/main/java/nl/talsmasoftware/umldoclet/uml/util/JavaBeanProperty.java
> Exclude static or abstract methods as property accessors

- src/main/java/nl/talsmasoftware/umldoclet/uml/DependencyDiagram.java
- src/main/java/nl/talsmasoftware/umldoclet/util/FileUtils.java
- src/test/java/nl/talsmasoftware/umldoclet/uml/DependencyDiagramTest.java
> Fix dependency-diagram.puml location for empty destination directory.

- .travis.yml
> Address travis buildfile warnings.

- src/main/java/nl/talsmasoftware/umldoclet/javadoc/UMLFactory.java
- src/test/java/nl/talsmasoftware/umldoclet/issues/Issue266Test.java
> Don't render static, abstract or non-public getter/setter methods as property

- src/main/java/nl/talsmasoftware/umldoclet/javadoc/dependencies/DependenciesElementScanner.java
- src/test/java/nl/talsmasoftware/umldoclet/javadoc/dependencies/PackageDependenciesTest.java
- src/test/java/nl/talsmasoftware/umldoclet/javadoc/dependencies/exceptions/TestException.java
> Include packages of thrown exceptions in package-dependencies.

- pom.xml
- src/main/java/nl/talsmasoftware/umldoclet/html/PackageDependenciesInserter.java
- src/main/java/nl/talsmasoftware/umldoclet/html/PackageDiagramInserter.java
> Build with jdk16

- usage.md
Thanks to Robin Kuijt (@rkuijt) for providing the Kotlin DSL example! 🏅 
Resolves #384
> Add Gradle Kotlin DSL example to usage document.

- src/main/java/nl/talsmasoftware/umldoclet/javadoc/LocalizedReporter.java
- src/test/java/nl/talsmasoftware/umldoclet/javadoc/LocalizedReporterTest.java
> Fix -verbose javadoc generation.

- pom.xml
> Remove unused maven-release-plugin.
